### ISSUE TITLE
renname+用不了，右键点了没反应，是哪里有问题？原作者的115rename却可以用

### ISSUE THREAD

**Issue by koollylee** [LSD08KM/115RenamePlus#17]

**Comment by Finetoo** [comment]
可以用，更新一下网站就行了。

**Comment by wbzdtmp** [comment]
我这里也有这个情况，研究后发现不知道为啥作者把 javbusBase 从 javbus.com 改成了 fanbus.blog ， 我这里改回来后就好了.
估计你那里也是哪个网站打不开导致的.

**Comment by LSD08KM** [comment]
> 我这里也有这个情况，研究后发现不知道为啥作者把 javbusBase 从 javbus.com 改成了 fanbus.blog ， 我这里改回来后就好了. 估计你那里也是哪个网站打不开导致的.

那是网站的防屏蔽地址，能不用代理直接访问。后来地址更换太频繁，没跟上更新....
