### ISSUE TITLE
FC2的用不了了，没有任何响应，网址是对的。

### ISSUE THREAD

**Issue by Finetoo** [LSD08KM/115RenamePlus#18]
FC2的用不了了，没有任何响应，网址是对的adult.contents.fc2.com/article/，我没学过代码，能看懂的地方就是ulr那里逻辑也是对的，例如fc2-ppv-1180724，实际网址就是https://adult.contents.fc2.com/article/1180724/。后面的分析fc2编号逻辑看着也是对的，剩下的看不懂，也不知道怎么改。

**Comment by LSD08KM** [comment]
要先在浏览器访问一次FC2，跳过初次访问的成年人选项

**Comment by LSD08KM** [comment]
关闭issu
