### ISSUE TITLE
如果多个文件同时修改时会被禁止访问一段时间

### ISSUE THREAD

**Issue by laiiwu** [LSD08KM/115RenamePlus#19]
多个文件，比如10个同时改名时会被认为是攻击行为，刷新网页显示如下
———
418
您的请求疑似攻击行为！
事件ID：一串数字
如果您是站长，您可以前往WAF控制台进行误报屏蔽设置，让您的访问不再被拦截

**Comment by LSD08KM** [comment]
是115升级了WAF，建议不要批量用了

**Comment by laiiwu** [comment]
> 是115升级了WAF，建议不要批量用了

每次改名请求后加一个延时是否可以避免触发防御机制？
